### PR TITLE
Fix Docker tags

### PR DESCRIPTION
**Pull request by joelchen**

### CODE REVIEW

**Comment by tboerger** [comment]
0.5 should be the recommended tag because nobody wants to update the docs on every minor release

**Comment by tboerger** [comment]
Beside that you should just talk about your plans in the Gitter chat, that can avoid some work for you

**Comment by bradrydzewski** [comment]
I'm not tagging `0.5` at the moment so we only have `0.5.0`. We'll need to ether update the docs or update the deployment script to tag `0.5` and `0.5.X` simultaneously. I'm fine with either.

**Comment by tboerger** [comment]
To keep it simple I would just add the 0.5 tag

**Comment by gtaylor** [comment]
We'll re-visit as we get closer to release. Going to close this PR, since it's not something we can act on yet.

**Pull request closed without merging**
