### PR TITLE
Add websocket configuration

### PR DESCRIPTION
**Pull request by strk**
tested, works for me.
rebased against release/0.5

@gtaylor

### CODE REVIEW

**Comment by gtaylor** [comment]
@strk I haven't played with apache in ages, so apologies if this is a stupid question: What was the reasoning behind having three separate websockets enpoints rather than a single that points at the topmost URL path (/api)?

IE:
```
ProxyPass /api/ ...(etc)
```

**Comment by strk** [comment]
I've understood not all /api endpoints are using websockets,
those which don't would fail if they were proxied with ws://.

I'd double-check but would rather first ensure to have a fully
working system (there's an issue with prematurely closing
connections for some long pullings).

**Comment by gtaylor** [comment]
I _think_ we have to request the upgrade on our side before it'll happen, which would make it safe to do the blanket / or /api like the other two examples. I could be wrong, though.

**Comment by strk** [comment]
I've tested by proxying to a port on which I put netcat listening
and seen the upgrade being requested by Apache itself whenever
it has "ws://" on the right-side of the ProxyPass directive.

This is different from the nginx setup where Upgrade/Connection
headers are copied verbatim from outer request to inner request
(unfortunately).

Maybe someone with more Apache experience will know how to do
that, I just found this other way for now.

**Comment by gtaylor** [comment]
Ahh, ok. Let's merge this in and iterate as needed. People are usually eager to contribute further tweaks as needed, and I don't have the relevant experience to say that this is the incorrect way. It addresses a doc gap, so let's do it!

LGTM

**Pull request merged**
