### PR TITLE
added example of negative when in publish block

### PR DESCRIPTION
**Pull request by a-buck**
Thought this might be helpful. It's something I didn't realise was possible until asking in a support channel

### CODE REVIEW

**Comment by tboerger** [comment]
You just need to look at the correct place. http://readme.drone.io/usage/deploy/#conditions:0814af543608f4fd171b2e9cf43d9917 already documents this behavior.

**Comment by a-buck** [comment]
Hi @tboerger, that's true but the only place it's documented is under `deployment` and I don't think it's obvious to look under there if you are working on a `publish` block. Please feel free to reject the PR if you don't think it's helpful. Cheers

**Comment by tboerger** [comment]
As the conditions are working for nearly all parts it just needs to be on a proper place so that everybody can find it

**Comment by tboerger** [comment]
But we should not duplicate this part of the documentation

**Comment by gtaylor** [comment]
We really need a dedicated "Conditional Execution" page, I think. We could then link all of these various cases (Deploy, Publish, Build, etc) there. I always forget which of the current pages to look at for whatever example I'm trying to find, I know it's got to be confusing to others as well.

**Comment by bradrydzewski** [comment]
The reason we have conditions on every page (and not a central page) is because when they were on a central page, people didn't see them. This is why I put the conditions inline with each section. There was a noticeable reduction in the number of issues / questions being asked about conditions once this change was made.

**Comment by gtaylor** [comment]
In the case of the negative example, should we add those to the others, or should we create a separate page *and* leave everything as-is aside for adding additional links to the more detailed page? Might be the best of both worlds.

**Comment by bradrydzewski** [comment]
> In the case of the negative example, should we add those to the others, or should we create a separate page and leave everything as-is aside for adding additional links to the more detailed page? Might be the best of both worlds.

I think we should duplicate across all pages (publish, deploy, notify). I think we've seen a dramatic reduction in the number of people asking about conditions, so we should only re-structure things where people keep asking the same question multiple times, indicating discoverability issues in the docs

**Comment by gtaylor** [comment]
:+1: Given that, is this safe to merge as-is?

**Pull request merged**
