### PR TITLE
Adding some additional links to plugin docs.

### PR DESCRIPTION
**Pull request by gtaylor**
As per http://discuss.drone.io/t/additional-plugin-doc-links/23/1, this PR adds some additional links to plugin docs:

image

Since this is a bit of a departure from what we're currently doing, going to wait for @bradrydzewski 's input on whether he wants this or not.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
I'd like to avoid direct links to the issue trackers. Given the nature of Drone (running untrusted code in containers) we have had problems with many false positive issues in the past. Pushing people toward Gitter (and now Discourse) has made life much easier on my end

**Comment by gtaylor** [comment]
Would it make sense to link to the "Help" category in Discourse in place of the issue tracker?

**Comment by bradrydzewski** [comment]
yes, definitely, Discourse can become our filter for false positives and duplicates. Less noisy than Gitter and searchable. Hopefully it will make a big difference

**Comment by gtaylor** [comment]
@bradrydzewski Revised this as follows:

image

**Comment by gtaylor** [comment]
@bradrydzewski Just wanted to be 100% sure you were OK with this before I merged. I think you were saying you're good, but wanted to get a for-sure "Yes".

**Comment by bradrydzewski** [comment]
LGTM

**Comment by gtaylor** [comment]
Post-merge, LGTM

**Pull request merged**
