### PR TITLE
add duration string reference link

### PR DESCRIPTION
**Pull request by carlwgeorge**
This has come up a few times in gitter, so I figured it's worth documenting.

### CODE REVIEW

**Comment by tboerger** [comment]
Can you confirm that these links are also working correctly within Hugo?

**Comment by carlwgeorge** [comment]
Yes, everything renders correctly with hugo and the links are functional.

**Comment by tboerger** [comment]
LGTM

**Comment by gtaylor** [comment]
TIL. Thanks!

**Pull request merged**
