### PR TITLE
Add Windows installation instructions for CLI

### PR DESCRIPTION
**Pull request by jhasse**
I've tested these with Docker Toolbox 1.11.2 and they work fine :)

### CODE REVIEW

**Comment by tboerger** [comment]
Curl and Tar on a windows system?

**Comment by jhasse** [comment]
Yes, Docker Toolbox comes with these Unix tools.

**Comment by gtaylor** [comment]
Thanks for the PR, @jhasse. The 0.4 docs (currently in master) are frozen pending the 0.5 release. See the release/0.5 branch. I think we've got some docs for the upcoming 0.5 install, but they may or may not need updating: https://github.com/drone/docs/blob/release/0.5/content/reference/cli/overview.md#install-on-windows

Going to close this due to the freeze, but feel free to test what we've got in release/0.5 and send PRs against that.

Sorry for the confusion!

**Comment by tboerger** [comment]
IMHO we should still accept doc improvements and provide the docs versioned for 0.4 and 0.5 at the same time

**Comment by Fleshgrinder** [comment]
I had to join Gitter and ask there because it is impossible to build drone from the sources on Windows and there is no download link nowhere. You should definitely merge this PR since right now interested users are pretty much f*****.

**Comment by jhasse** [comment]
Can this be merged? CLI for 0.5 isn't ready yet, so this is a working solution.

**Comment by tboerger** [comment]
The 0.4 docs are frozen. Beside that is a bin folder wrong or not?

**Comment by jhasse** [comment]
> Beside that is a bin folder wrong or not?

What do you mean with "wrong"? I've tested these instructions with a clean Docker Toolbox installation on Windows 10, no other configuration was necessary. It seems that the Docker Toolbox automatically creates this bin folder and adds it to the path, when starting the Quickstart Terminal.

**Comment by tboerger** [comment]
Ok, didn't know about that

**Pull request closed without merging**
