### PR TITLE
Add Generate private key file section.

### PR DESCRIPTION
**Pull request by appleboy**
Improve private key section on bitbucket server document.

http://readme.drone.io/0.5/installation/services/bitbucet_server/

### CODE REVIEW

**Comment by josmo** [comment]
Thanks @appleboy, might also be useful to add that the public key needs to go in the incoming link part of the application registration.

**Comment by appleboy** [comment]
@josmo I update the `Registration` section. Please review again.

**Comment by josmo** [comment]
@appleboy  sounds good. Looks like it will be a bit more clear for folks. :)

**Comment by appleboy** [comment]
@josmo Thanks for your help. 👍

**Comment by appleboy** [comment]
@bradrydzewski Can you merge this PR and update the readme.drone.io?

**Comment by gtaylor** [comment]
@appleboy Please try not to @-mention Brad directly unless there's an urgent need. He's trying to get 0.5 wrapped up.

We'll be able to get this reviewed and merged.

**Comment by appleboy** [comment]
@gtaylor OK.

**Pull request merged**
