### PR TITLE
removed doc about failed steps and stages

### PR DESCRIPTION
**Pull request by prune998**
DRONE_FAILED_STEPS and DRONE_FAILED_STAGES env variables does not exist at all in the Drone code...

### CODE REVIEW

**Comment by bradrydzewski** [comment]
these variables exist here:
https://github.com/drone/runner-go/blob/master/environ/environ.go#L82:L84

all variables are set in these files:
https://github.com/drone/runner-go/blob/master/environ/environ.go
https://github.com/drone/runner-go/blob/master/environ/semver.go
https://github.com/drone/runner-go/blob/master/environ/calver.go

**Comment by prune998** [comment]
They exist, but from what I'm understanding they will never be set... an I wrong assuming that ? 
Please, @bradrydzewski , if I'm wrong, just explain me in which condition they are set and how to use them... It will be a pleasure to improve the documentation and do another PR.
Thanks.

**Comment by bradrydzewski** [comment]
the values are set, for example: https://cloud.drone.io/drone/hello-world/170/1/4

**Comment by prune998** [comment]
Thanks. My bad, this is working for Docker runner. I don't see it working with Kubernetes though... 
using:
```
---
kind: pipeline
type: kubernetes
name: default

steps:

- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - exit 1

- name: dump
  image: alpine:3.8
  commands:
  - cat /run/drone/env
  - env
  when:
    status: [failure]

service:
- name: cache
  image: redis
```

I'll keep digging, thanks for your help.

**Pull request closed without merging**
