### PR TITLE
Update Webhook plugin documentation regarding SSL

### PR DESCRIPTION
**Pull request by imranismail**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
usage details are contained in the `DOCS.md` file in the root of the repository and is used to automatically generate the official plugin documentation at http://readme.drone.io/plugins/webhook/

feel free to send a PR that updates the DOCS.md file

**Comment by bradrydzewski** [comment]
sorry, meant to say this file https://github.com/drone-plugins/drone-webhook/blob/master/DOCS.md

so all documentation changes for plugins need to go to the plugin repository, since the plugin documentation in this repository is auto-generated

**Comment by imranismail** [comment]
I see, that's so cool! Okay will send a PR

**Comment by imranismail** [comment]
It's already there 👍

**Pull request closed without merging**
