### PR TITLE
Add tmpfs

### PR DESCRIPTION
**Pull request by alexislefebvre**
Source: https://discourse.drone.io/t/is-it-possible-to-use-tmpfs-for-services-volumes-on-drone-1-0/4312/2

### CODE REVIEW

**Comment by alexislefebvre** [comment]
It's not specific to kubernetes but it looks like it complements this page: https://docs.drone.io/pipeline/kubernetes/syntax/volumes/temporary/

**Comment by bradrydzewski** [comment]
:wave: hey there, we have an existing page for temporary volumes:
https://github.com/drone/docs/blob/e7c4c6478babd3ab78403793a917b37ea57fb41c/content/pipeline/kubernetes/syntax/volumes/temporary.md

I recommend adding a new section to this existing page for the `memory` setting.

**Comment by alexislefebvre** [comment]
Ok thanks, I updated the existing page. :heavy_check_mark:

**Review by tphoney — APPROVED** [review]
Thanks for the addition @alexislefebvre

**Pull request merged**
