### PR TITLE
Add documentation about entrypoint and command

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @tboerger @bradrydzewski

### CODE REVIEW

**Comment by tboerger** [comment]
I don't really like the wording. With entrypoint and command you can override the entrypoint or cmd directives of the service image. You don't need to set both and you can also call the binary from the command section

**Comment by MorrisJobke** [comment]
> I don't really like the wording. With entrypoint and command you can override the entrypoint or cmd directives of the service image. You don't need to set both and you can also call the binary from the command section

Thanks :) Fixed

**Comment by tboerger** [comment]
I don't wanted to say that you take it word by word. And I would suggest to split it into 2 paragraphs, 1 for Entrypoint and 1 for Command like the other paragraphs.

**Comment by MorrisJobke** [comment]
> I don't wanted to say that you take it word by word. And I would suggest to split it into 2 paragraphs, 1 for Entrypoint and 1 for Command like the other paragraphs.

🙈 it's late - I will have a look tomorrow :)

**Comment by gtaylor** [comment]
I tweaked this a bit, but let's get this in here for completeness!

**Comment by MorrisJobke** [comment]
> I tweaked this a bit, but let's get this in here for completeness!

Thanks a lot - sorry - I was just busy with other stuff.

**Pull request merged**
