### PR TITLE
Set text/html for files w/o extension

### LINKED ISSUE #300: Link to 0.8.4 release on docs.drone.io has incorrect content-type causing the page to be downloaded as a file.
Also the 0.8.4 release out of order, below 0.8.0 which is kinda odd

### PR DESCRIPTION
**Pull request by tonglil**
Closes #300.

### CODE REVIEW

**Comment by tonglil** [comment]
Thanks!

**Comment by tonglil** [comment]
Mm, it didn't seem to change anything on my end.

Possibilities:
- Cached somewhere (can't check)
- Not overwriting S3 (can't check)
- Maybe I need to quote the content type?

**Comment by bradrydzewski** [comment]
what about this:

```diff
-"": text/html; charset=utf-8
+".4": text/html; charset=utf-8
```

or even better, would this work?

```diff
-"": text/html; charset=utf-8
+".*": text/html; charset=utf-8
```

It looks like amazon is treating `.4` as an extension

**Comment by tboerger** [comment]
I would prefer renaming the pages.

**Pull request merged**
