### PR TITLE
Adding agent based filtering info

### PR DESCRIPTION
**Pull request by hnykda**
Trying to solve #364 . Mostly taken from [test suite](https://github.com/drone/expr/blob/master/selector_test.go) and [here](https://github.com/drone/drone/pull/2200#issuecomment-328394983).

### CODE REVIEW

**Comment by hnykda** [comment]
Great to here! Any feedback on testing this is welcome.

**Comment by thefab** [comment]
seems to be really clear to me but...

```
drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=xxxxxxxxxxxxxxxxxxxxx
      - DRONE_DEBUG=true
      - DRONE_FILTER="repo != 'metwork-framework/mfext'"
```

And i got in agent logs:

```
{"time":"2018-09-17T08:56:07Z","level":"error","error":"rpc error: code = Unknown desc = selector: parse error:0: illegal value expression","message":"pipeline done with error"}
```

Did I miss something ? Or this feature is not available in 0.8 branch ?

**Comment by bradrydzewski** [comment]
you should not quote docker environment variables. docker does not unquote them when it parses the yaml

```diff
  environment: 
- - DRONE_FILTER="repo != 'metwork-framework/mfext'"
+ - DRONE_FILTER=repo != 'metwork-framework/mfext'
```

**Comment by jmccann** [comment]
@bradrydzewski brings up a good point ...

Does https://github.com/drone/docs/pull/365/files#diff-9e57d9a3f73e1bb392b686d8a92afad2R39 need to be updated to reflect that?

Also, does

```
  environment: 
    - DRONE_FILTER=repo != 'metwork-framework/mfext'
```

"just work"?  I'm worried with the spaces and special characters but admit I've not tried it myself

**Comment by bradrydzewski** [comment]
yep, docker does a `strings.Split(s, "=", 2)` and then uses a system call to the sent the environment variable. Quoting or escaping values is not required when invoking the syscalls directly.

**Comment by thefab** [comment]
with 

```
environment: 
    - DRONE_FILTER=repo != 'metwork-framework/mfext'
```

my agent starts ! (thanks) but...

```
$ docker inspect 37b17a78a9a9 |grep DRONE_FILTER

                "DRONE_FILTER=repo != 'metwork-framework/mfext'",

```

and

```
$ docker logs -f 37b17a78a9a9

[...]
{"time":"2018-09-18T07:03:33Z","level":"debug","repo":"metwork-framework/mfext","build":"108","id":"2451","image":"metwork/mfext-centos6-buildimage:integration","stage":"build","message":"log stream opened"}
```

So, every thing seems to be ok but the agent does not filter !

```
$ docker images |grep drone/agent
drone/agent                           0.8                 ea280fb03b0a        7 weeks ago         13.7MB
```

Is it a feature specific to 0.9 version ? (I use the 0.8 branch)

**Comment by hnykda** [comment]
I removed the quotes and added the info about not-quoting. Not sure which branch this applies to :grimacing:, I believe it should be there since 0.8 already .

**Comment by thefab** [comment]
after several days, does not work for me on 0.8 branch for "repo" or "repo-name" filter:

```
$ # FIRST AGENT
$ docker inspect b648b8d9fe4e |grep FILTER
                "DRONE_FILTER=repo-name != 'mfext'",

$ docker logs b648b8d9fe4e 2>&1 |grep mfext
[...]
{"time":"2018-09-24T11:00:45Z","level":"debug","repo":"metwork-framework/mfext","build":"145","id":"7831","message":"pipeline done"}


$ # SECOND AGENT
$ docker inspect 7ef92464be55 |grep FILTER
                "DRONE_FILTER=repo-name == 'mfext'",

$ docker logs 7ef92464be55
{"time":"2018-09-19T11:57:27Z","level":"debug","message":"request next execution"}
=> no build
```

no more luck with filtering on "repo" (instead of repo-name)

The filtering seems to work a little bit because I have no build on second agent. Maybe I miss something on filtering on repo name ?

**Comment by hnykda** [comment]
Are you able to test it with e.g. 0.9?

**Comment by bradrydzewski** [comment]
the behavior changed to the following in 0.9.* and higher:
https://docs.drone.io/reference/agent/drone-runner-labels/
https://docs.drone.io/config/pipeline/nodes/

since this is now documented in the latest version I'm going to close this issue.

**Comment by hnykda** [comment]
Great, thanks.

**Comment by SmajeNz0** [comment]
Hello

https://docs.drone.io/config/pipeline/nodes/

Little typo in### **ts**ance insted of instance.

**Pull request closed without merging**
