### PR TITLE
Correct agent docker image in Gitea integration doc

### PR DESCRIPTION
**Pull request by svarlamov**

### CODE REVIEW

**Comment by tboerger** [comment]
Scratch my approval.

**Comment by svarlamov** [comment]
@tboerger It didn't work for me like that on 0.8. Also, why would the Gitea integration be different from http://docs.drone.io/installation/ where it uses the agent image?

**Comment by svarlamov** [comment]
Also, worth noting, every single other integration document uses the `agent` image. Not saying that we should be following the crowd, but that would at least deserve a mention in the doc as to why that is the case...

**Comment by tboerger** [comment]
The agent is using the agent image, but not the server like you changed it ;)

**Comment by svarlamov** [comment]
@tboerger Sharp eyes! Thank you for the fix

**Pull request merged**
