### PR TITLE
Fix #196 - Update 0.5 docs with nginx reverse proxy

### LINKED ISSUE #196: Update 0.5 nginx reverse documentation
- [x] Update `0.5` documentation with working reverse proxy config for nginx.

### PR DESCRIPTION
**Pull request by mbeacom**
Resolves issue #196

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by mbeacom** [comment]
@tboerger Thank you for the `LGTM`!  However, I committed a comment change directly after you added the comment.  Any way to get another all clear? 🍀

**Comment by tboerger** [comment]
Now you mixed tabs and spaces :)

**Comment by mbeacom** [comment]
@tboerger Sorry about that.  Should be all set. 👍

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
