### PR TITLE
fixed typo in content/install/integrations/github.md

### PR DESCRIPTION
**Pull request by dance-cmdr**

### CODE REVIEW

**Comment by tboerger** [comment]
Brad has not uploaded the latest docs version to this repo, so it's possible that it will be overwritten anyway.

**Comment by myth** [comment]
@tboerger Could you encourage him to do so? Now that 1.0.0 is out, there are several small typos and copy pasta errors the community would benefit from being able to fix by submitting PRs.

**Comment by dance-cmdr** [comment]
Good to know you are working on that in the new version. 

However, I want to ask something else that might need a new issue of it's own.
Do you plan to watermark the docs with the version number? We get a huge pain on determinging which version of the docs I was looking at already.
Do you plan to have a version switch on your docs. It would also benefit a lot of people if we could switch doc version. For example some teams, for different reasons, do not have the bandwith to migrate to the lates versions.

**Comment by tboerger** [comment]
> However, I want to ask something else that might need a new issue of it's own.
> Do you plan to watermark the docs with the version number? We get a huge pain on determining which version of the docs I was looking at already.
> Do you plan to have a version switch on your docs? It would benefit a lot of people if we could switch doc version. For example some teams, for different reasons, do not have the bandwith to migrate to the latest version.

On the docs for current LTS version 1.0.0 you can see the version on the bottom right.

**Pull request closed without merging**
