### PR TITLE
Fix apache reverse proxy for logs/ endpoint

### PR DESCRIPTION
**Pull request by strk**
Only GET method should be upgraded to websockets, not POST

### CODE REVIEW

**Comment by strk** [comment]
Note: drone failure is unrelated (fatal: Couldn't find remote ref refs/pull/155/merge)

**Comment by gtaylor** [comment]
I think @bradrydzewski is working on a websocket endpoint refactor right this second. Is it cool to sit on this until he's got that shaken out? Sounds like it could be on the top of his to-do list atm.

**Comment by strk** [comment]
Does 0.4 have completely different endpoints ?

**Comment by tboerger** [comment]
0.4 doesn't use websockets at all, it's based on server sent events (SSE)

**Comment by strk** [comment]
In that case you decide what to do with the config.

I knew it was going to change but as I'm already running 0.5
I did need a working Apache config. The configuration in this
PR seems to work fine (at least for logs).

Personally I think it's good for published docs to match
published code. If it will still work after the code changes
I think it'd make sense to publish anyway, and cleanup later.

**Comment by gtaylor** [comment]
@strk Any idea if this is still functioning with the latest 0.5 master?

**Comment by strk** [comment]
Not really. I think I'm using it with
commit ae418bf063907d4081b9dd7c3f787002cdacb049
what changed in routing since then ?

**Comment by gtaylor** [comment]
Looks like this is still in-progress. We'll be transitioning to WAMP and potentially changing URL structure.

**Comment by strk** [comment]
I've recently upgraded to current master branch (5130919869a1cf855975870fdf9ac72624f53be5) and I confirm the proxy configuration still works fine there.

What's WAMP, btw ?

**Comment by gtaylor** [comment]
I'm not sure that these protocol adjustments have been made yet, so it'd make sense that things still work.

**Comment by strk** [comment]
For those like me who are already running Drone from the master
branch it would make sense to also find a working config in the
online documentation. How about merging this PR and changing the
docs only when the code actually changes ? It's been some time
now that the proposed documentation is still valid..

**Comment by gtaylor** [comment]
Is this still wrking, @strk? Sounds like the broker stuff landed.

**Comment by strk** [comment]
Landed in which commit ? I might upgrade to check...

**Comment by gtaylor** [comment]
I'm not sure off the top of my head. Brad made an announcement about the big MQ merge a few days ago, so very recently.

Sorry I'm not more helpful. Currently on leave.

**Comment by strk** [comment]
@bradrydzewski: can you help here ?
What changed wrt websocket urls ?

**Comment by bradrydzewski** [comment]
see https://discuss.drone.io/t/installing-drone-drone-0-5-with-latest-breaking-changes/338/1

**Comment by strk** [comment]
Ok after reading that blog post the change in this PR seems useless.
The first ProxyPass should theoretically be enough for everything, so it could still be worth a change removing all the rest (but would need to test it first). Anyway, let's just close this.

**Pull request closed without merging**
