### PR TITLE
You have to add image to customize cloning

### PR DESCRIPTION
**Pull request by sergeyz**

### CODE REVIEW

**Comment by gtaylor** [comment]
Are you sure? I don't recall having to do this in the past.

cc @bradrydzewski

**Comment by bradrydzewski** [comment]
@gtaylor yes, this is a new change. I removed a lot of the "magic" that auto-populated or mutated the `image` sections of the yaml in favor of asking configuration files to be explicit.

**Comment by gtaylor** [comment]
Ahh, OK. Makes sense.

@sergeyz If you want to update the rest of the examples in this file to explicitly show the override, we can get this merged.

**Comment by sergeyz** [comment]
@gtaylor done

**Comment by tboerger** [comment]
LGTM

**Comment by gtaylor** [comment]
LGTM. Thanks for the PR!

**Pull request merged**
