### PR TITLE
Update plugin docs

### PR DESCRIPTION
**Pull request by mickeyreiss**
I noticed that a number of the pages under https://readme.drone.com/plugins were out of date.

To create this PR, I ran `go run ./contrib/plugin-gen-all.go` and kept only the changes with content updates.

Hope this helps!

### CODE REVIEW

**Comment by tboerger** [comment]
This won't work, you are updating the 0.4 docs with data from 0.5.

**Comment by mickeyreiss** [comment]
😞

**Comment by tboerger** [comment]
We will work something out to make it automated for 0.5 ;)

**Comment by mickeyreiss** [comment]
That sounds great, thanks! I had submitted this PR because I had noticed that a few of the undocumented options already do seem to work for me in 0.4. Unfortunately, I don't have enough context on the project yet to understand exactly how drone versions and plugin versions interact.

**Pull request closed without merging**
