### PR TITLE
Adding the Apache 2.0 License.

### PR DESCRIPTION
**Pull request by gtaylor**
Saw #110, figured I'd float this over for @bradrydzewski to thumb up or down. Seems like most of our stuff is Apache 2.0, so there's a good chance that this is what Brad intended.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by bradrydzewski** [comment]
since most of this is content-based, what about something like creative commons? I'm thinking this one http://creativecommons.org/licenses/by-sa/4.0/

**Comment by tboerger** [comment]
Great idea

**Comment by bradrydzewski** [comment]
I added a creative commons license, but if that ends up being insufficient we can always change

**Comment by gtaylor** [comment]
:+1:

**Pull request closed without merging**
